### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by abubelinha** [martgnz/es-atlas#12]
Disclaimer: I am an absolute newbie to node.

I just tried to follow the installation instructions and this is what happened:

```
myusername@debian:~/home/node/$ mkdir atlas
myusername@debian:~/home/node/$ cd atlas
myusername@debian:~/home/node/atlas$ wget https://github.com/martgnz/es-atlas/archive/refs/heads/master.zip
myusername@debian:~/home/node/atlas$ unzip master.zip
myusername@debian:~/home/node/atlas$ cd es-atlas-master
myusername@debian:~/home/node/atlas/es-atlas-master$ npm install

> es-atlas@0.2.1 prepare /home/node/atlas/es-atlas-master
> bash prepublish $npm_package_config_with_names $npm_package_config_simplification $npm_package_config_quantization $npm_package_config_autonomous_regions

Autonomous regions: all
Simplification: 0.0001
Quantization: 10000
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  118M    0  118M    0    46  2477k      0 --:--:--  0:00:49 --:--:-- 2303k
Archive:  build/lineas_limite.zip
caution: filename not matched:  recintos_municipales*
caution: filename not matched:  recintos_provinciales*
caution: filename not matched:  recintos_autonomicas*

  error: ENOENT: no such file or directory, open 'build/recintos_autonomicas_inspire_peninbal_etrs89.shp'


  error: ENOENT: no such file or directory, open 'build/recintos_autonomicas_inspire_canarias_wgs84.shp'


  error: expected GeometryCollection, not null


  error: ENOENT: no such file or directory, open 'build/recintos_provinciales_inspire_peninbal_etrs89.shp'


  error: ENOENT: no such file or directory, open 'build/recintos_provinciales_inspire_canarias_wgs84.shp'


  error: expected GeometryCollection, not null

undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Socket.<anonymous> (/home/node/atlas/es-atlas-master/node_modules/topojson-client/bin/topomerge:76:46)
    at Socket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

  error: ENOENT: no such file or directory, open 'build/recintos_municipales_inspire_peninbal_etrs89.shp'


  error: ENOENT: no such file or directory, open 'build/recintos_municipales_inspire_canarias_wgs84.shp'


  error: expected GeometryCollection, not null

undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Socket.<anonymous> (/home/node/atlas/es-atlas-master/node_modules/topojson-client/bin/topomerge:76:46)
    at Socket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Socket.<anonymous> (/home/node/atlas/es-atlas-master/node_modules/topojson-client/bin/topomerge:76:46)
    at Socket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ReadStream.<anonymous> (/home/node/atlas/es-atlas-master/node_modules/topojson-client/bin/topo2geo:31:46)
    at ReadStream.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
cat: es/_border.jsoncat: es/_autonomous_regions.json: No such file or directory
: No such file or directory
undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ReadStream.<anonymous> (/home/node/atlas/es-atlas-master/node_modules/topojson-client/bin/topo2geo:31:46)
    at ReadStream.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
cat: es/_autonomous_regions.jsoncat: es/_border.json: No such file or directory
: No such file or directory
cat: es/_provinces.json: No such file or directory
rm: cannot remove 'es/_provinces.json': No such file or directory
rm: cannot remove 'es/_autonomous_regions.json': No such file or directory
rm: cannot remove 'es/_border.json': No such file or directory
undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ReadStream.<anonymous> (/home/node/atlas/es-atlas-master/node_modules/topojson-client/bin/topo2geo:31:46)
    at ReadStream.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
cat: es/_provinces.json: No such file or directory
cat: cat: es/_municipalities.json: No such file or directoryes/_autonomous_regions.json
: No such file or directory
cat: es/_border.json: No such file or directory
rm: cannot remove 'es/_municipalities.json': No such file or directory
rm: cannot remove 'es/_provinces.json': No such file or directory
rm: cannot remove 'es/_autonomous_regions.json': No such file or directory
rm: cannot remove 'es/_border.json': No such file or directory
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! es-atlas@0.2.1 prepare: `bash prepublish $npm_package_config_with_names $npm_package_config_simplification $npm_package_config_quantization $npm_package_config_autonomous_regions`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the es-atlas@0.2.1 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/myusername/.npm/_logs/2021-04-01T17_39_43_775Z-debug.log
```

**Comment by abubelinha** [comment]
My only interest in installing this is to run it using the `with-names` option 

So if this linked file contained geographical names, it would probably be just OK for me:
https://unpkg.com/es-atlas/es/municipalities.json

But when I upload the json to postgresql with ogr2ogr there are no names in it: only ids for geographical entities.

```
myusername@debian:$ ogr2ogr -f "PostgreSQL" PG:"dbname=mydatabase user=myusername" "/path/to/municipalities.json"
myusername@debian$ sudo -i -u postgres
postgres@debian:$ psql
postgres=# \c mydatabase
mydatabase=# \d
... List of relations (autonomous_regions, border, municipalities and provinces)
mydatabase=# \d municipalities
```
... which produces the following output:

**Table "public.municipalities"**

| Column | Type | Collation | Nullable | Default
| ------------- | ------------- | ------------- | ------------- | ------------- |
ogc_fid | integer | | not null | nextval('municipalities_ogc_fid_seq'::regclass)
| wkb_geometry | bytea             |           |          |
| id           | character varying |           |          |

**Indexes:**
    "municipalities_pkey" PRIMARY KEY, btree (ogc_fid)

-------------------
Is there any quick way I can download the geographical names corresponding to each id, even if they are in a separate table?
 
Of course, if @martgnz or anyone else could generate a **municipalities_with_names.json** file for me, I would be so grateful !!

Many thanks in advance

**Comment by martgnz** [comment]
Sorry, for some reason the build stopped working, I think the folders inside the zip file changed a bit. I have pushed a new release, maybe you can try again?

**Comment by abubelinha** [comment]
Thanks a lot @martgnz 
Now it worked !!

But I have detected what I think is a different bug, so I will open a different issue #13.
